<?xml version="1.0"?>
<package format="2">
  <name>g5_openarm_ros</name>
  <version>0.0.1</version>
  <description>ROS2 launch package for g5_openarm OCS2 workflows.</description>

  <maintainer email="you@example.com">g5_openarm</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ocs2_mobile_manipulator_ros</depend>
  <depend>g5_openarm_description</depend>
  <depend>g5_openarm_ocs2</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
